=== ttlyceo/L2JTW_tautiV2.0/L2JTW_DataPack_Tauti/dist/game/data/xsd/skillReplace.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element name="skill" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="unbounded">
							<xs:element name="remove" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ttlyceo/L2JTW_tautiV2.0/L2JTW_DataPack_Tauti/dist/game/data/stats/skillReplace.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/skillReplace.xsd">
<!-- 覺醒技能-席格爾騎士 -->
	<skill id='10001'><!-- 極致精通劍鈍兵器 -->
		<remove id='205'/><!-- 精通劍鈍兵器1 -->
		<remove id='217'/><!-- 精通劍鈍兵器2 -->
		<remove id='257'/><!-- 精通劍鈍兵器3 -->
	</skill>
	<skill id='10002'><!-- 極致精通重裝甲 -->
		<remove id='191'/><!-- 精神凝聚 -->
		<remove id='231'/><!-- 精通重裝甲1 -->
		<remove id='232'/><!-- 精通重裝甲2 -->
		<remove id='253'/><!-- 精通重裝甲3 -->
		<remove id='259'/><!-- 精通重裝甲4 -->
		<remove id='291'/><!-- 最終要塞 -->
		<remove id='429'/><!-- 騎士精神 -->
	</skill>
	<skill id='10003'><!-- 極致精通盾技 -->
		<remove id='153'/><!-- 精通盾技 -->
		<remove id='316'/><!-- 庇護 -->
		<remove id='318'/><!-- 庇護之勢 -->
	</skill>
	<skill id='10004'><!-- 極致魔法抵抗 -->
		<remove id='147'/><!-- 魔法抵抗 -->
	</skill>
	<skill id='10005'><!-- 極致特性抵抗 -->
		<remove id='328'/><!-- 睿智 -->
		<remove id='329'/><!-- 健壯 -->
		<remove id='335'/><!-- 剛毅 -->
		<remove id='350'/><!-- 物理鏡射 -->
		<remove id='351'/><!-- 魔法鏡射 -->
	</skill>
	<skill id='10006'><!-- 最終忍耐 -->
		<remove id='983'/><!-- 忍耐 -->
	</skill>
	<skill id='10008'><!-- 盾牌突擊 -->
		<remove id='984'/><!-- 強力盾擊 -->
	</skill>
	<skill id='10009'><!-- 最終審判 -->
		<remove id='115'/><!-- 能量破壞 -->
		<remove id='400'/><!-- 裁決 -->
		<remove id='401'/><!-- 審判 -->
	</skill>
	<skill id='10010'><!-- 正義斷罪 -->
		<remove id='102'/><!-- 纏繞之足 -->
		<remove id='127'/><!-- 遲緩術 -->
	</skill>
	<skill id='10011'><!-- 盾牌衝擊 -->
		<remove id='92'/><!-- 衝擊盾 -->
		<remove id='352'/><!-- 重擊盾 -->
	</skill>
	<skill id='10013'><!-- 暴烈之刃 -->
		<remove id='49'/><!-- 神聖之擊 -->
		<remove id='105'/><!-- 冰凍之擊 -->
	</skill>
	<skill id='10015'><!-- 鎖鍊直擊 -->
		<remove id='402'/><!-- 逮捕 -->
		<remove id='403'/><!-- 拘束 -->
	</skill>
	<skill id='10016'><!-- 灼蛇鎖鍊 -->
		<remove id='107'/><!-- 神聖靈氣 -->
		<remove id='404'/><!-- 群體拘束 -->
	</skill>
	<skill id='10017'><!-- 最終極限防禦 -->
		<remove id='110'/><!-- 極限防禦 -->
	</skill>
	<skill id='10019'><!-- 信念加護 -->
		<remove id='528'/><!-- 信念之盾 -->
	</skill>
	<skill id='10020'><!-- 偵測之盾 -->
		<remove id='322'/><!-- 保護要塞 -->
	</skill>
	<skill id='10021'><!-- 刺棘之盾 -->
		<remove id='86'/><!-- 還擊 -->
		<remove id='916'/><!-- 魔法反射盾 -->
	</skill>
	<skill id='10025'><!-- 騎士誓言 -->
		<remove id='10'/><!-- 召喚暴風晶體 -->
		<remove id='22'/><!-- 召喚吸血晶體 -->
		<remove id='33'/><!-- 召喚干擾晶體 -->
		<remove id='65'/><!-- 戰慄 -->
		<remove id='67'/><!-- 召喚治癒晶體 -->
		<remove id='278'/><!-- 召喚毒蛇晶體 -->
		<remove id='406'/><!-- 天使聖靈 -->
		<remove id='449'/><!-- 召喚吸引晶體 -->
	</skill>
	<skill id='10026'><!-- 極致挑撥 -->
		<remove id='28'/><!-- 挑撥 -->
	</skill>
	<skill id='10027'><!-- 極致挑撥靈氣 -->
		<remove id='18'/><!-- 強力挑撥 -->
	</skill>
	<skill id='10028'><!-- 震怒靈氣 -->
		<remove id='982'/><!-- 戰鬥靈氣 -->
	</skill>
	<skill id='10030'><!-- 挑戰靈氣 -->
		<remove id='982'/><!-- 戰鬥靈氣 -->
	</skill>
	<skill id='10032'><!-- 鐵壁靈氣 -->
		<remove id='982'/><!-- 戰鬥靈氣 -->
	</skill>
	<skill id='10034'><!-- 抵抗靈氣 -->
		<remove id='982'/><!-- 戰鬥靈氣 -->
	</skill>
	<skill id='10036'><!-- 活力靈氣 -->
		<remove id='982'/><!-- 戰鬥靈氣 -->
	</skill>
	<skill id='10038'><!-- 精神靈氣 -->
		<remove id='982'/><!-- 戰鬥靈氣 -->
	</skill>
	<skill id='10040'><!-- 召喚金獅 -->
		<remove id='283'/><!-- 召喚黑暗豹 -->
	</skill>
	<skill id='10043'><!-- 召喚幻影晶體 -->
		<remove id='97'/><!-- 神聖庇護 -->
		<remove id='779'/><!-- 召喚聰慧晶體1 -->
		<remove id='780'/><!-- 召喚聰慧晶體2 -->
		<remove id='781'/><!-- 召喚聰慧晶體3 -->
		<remove id='782'/><!-- 召喚聰慧晶體4 -->
		<remove id='783'/><!-- 召喚聰慧晶體5 -->
	</skill>
	<skill id='10044'><!-- 極致精通元素 -->
		<remove id='197'/><!-- 神聖之衣 -->
	</skill>
<!-- 覺醒技能-提爾鬥士 -->
	<skill id='10251'><!-- 極致精通武器 -->
		<remove id='168'/><!-- 攻擊加速 -->
		<remove id='205'/><!-- 精通劍鈍兵器1 -->
		<remove id='210'/><!-- 精通拳技 -->
		<remove id='216'/><!-- 精通長戟 -->
		<remove id='217'/><!-- 精通劍鈍兵器2 -->
		<remove id='257'/><!-- 精通劍鈍兵器3 -->
		<remove id='330'/><!-- 精通戰技 -->
		<remove id='421'/><!-- 闊擊 -->
		<remove id='422'/><!-- 精準槍技 -->
		<remove id='472'/><!-- 精通古代劍 -->
	</skill>
	<skill id='10252'><!-- 極致精通二刀流 -->
		<remove id='144'/><!-- 精通二刀流 -->
		<remove id='293'/><!-- 精通雙手武器 -->
	</skill>
	<skill id='10253'><!-- 極致精通重裝甲 -->
		<remove id='231'/><!-- 精通重裝甲1 -->
		<remove id='232'/><!-- 精通重裝甲2 -->
		<remove id='253'/><!-- 精通重裝甲3 -->
		<remove id='259'/><!-- 精通重裝甲4 -->
	</skill>
	<skill id='10254'><!-- 極致精通輕裝甲 -->
		<remove id='227'/><!-- 精通輕裝甲1 -->
		<remove id='233'/><!-- 精通輕裝甲2 -->
		<remove id='236'/><!-- 精通輕裝甲3 -->
		<remove id='252'/><!-- 精通輕裝甲4 -->
		<remove id='258'/><!-- 精通輕裝甲5 -->
		<remove id='319'/><!-- 身手輕靈 -->
		<remove id='465'/><!-- 精通輕裝甲6 -->
		<remove id='832'/><!-- 速效恢復 -->
	</skill>
	<skill id='10255'><!-- 極致精通鬥力 -->
		<remove id='992'/><!-- 精通波動 -->
		<remove id='993'/><!-- 精通鬥氣 -->
	</skill>
	<skill id='10256'><!-- 極致精通HP -->
		<remove id='148'/><!-- 生命之原 -->
		<remove id='211'/><!-- 生命強化 -->
		<remove id='212'/><!-- 快速生命恢復 -->
		<remove id='290'/><!-- 最終狂擊 -->
	</skill>
	<skill id='10257'><!-- 極致精通精神 -->
		<remove id='328'/><!-- 睿智 -->
		<remove id='329'/><!-- 健壯 -->
	</skill>
	<skill id='10258'><!-- 戰甲壞滅 -->
		<remove id='1'/><!-- 三連斬 -->
		<remove id='116'/><!-- 怒嚎 -->
		<remove id='190'/><!-- 致命侵襲 -->
		<remove id='281'/><!-- 破滅靈魂 -->
		<remove id='284'/><!-- 風暴之擊 -->
		<remove id='362'/><!-- 破甲壞擊 -->
		<remove id='501'/><!-- 暴戾之氣 -->
		<remove id='920'/><!-- 強力碎擊 -->
	</skill>
	<skill id='10260'><!-- 爆裂直擊 -->
		<remove id='5'/><!-- 波動連斬 -->
		<remove id='280'/><!-- 赤燄之拳 -->
		<remove id='492'/><!-- 展翅 -->
		<remove id='921'/><!-- 暴烈穿刺 -->
	</skill>
	<skill id='10262'><!-- 強力炸彈 -->
		<remove id='81'/><!-- 破滅之擊 -->
		<remove id='261'/><!-- 波動三連斬 -->
		<remove id='315'/><!-- 破滅爆碎 -->
		<remove id='498'/><!-- 迸裂 -->
	</skill>
	<skill id='10263'><!-- 暴風衝擊 -->
		<remove id='345'/><!-- 波動劍震 -->
		<remove id='346'/><!-- 鬥拳氣破 -->
		<remove id='939'/><!-- 靈魂暴怒 -->
	</skill>
	<skill id='10265'><!-- 鬥力放射 -->
		<remove id='9'/><!-- 波動爆破 -->
		<remove id='17'/><!-- 爆裂之力 -->
		<remove id='36'/><!-- 槍舞旋風 -->
		<remove id='496'/><!-- 刀刃連斬 -->
	</skill>
	<skill id='10266'><!-- 巨人之拳 -->
		<remove id='48'/><!-- 怒雷風暴 -->
		<remove id='95'/><!-- 癱瘓術 -->
		<remove id='260'/><!-- 昏迷衝擊 -->
		<remove id='452'/><!-- 奔雷腳 -->
		<remove id='477'/><!-- 黑暗破擊 -->
		<remove id='497'/><!-- 劇痛碎擊 -->
	</skill>
	<skill id='10268'><!-- 閃電迴旋 -->
		<remove id='423'/><!-- 煉獄之體 -->
	</skill>
	<skill id='10269'><!-- 跳躍攻擊 -->
		<remove id='793'/><!-- 疾襲衝擊1 -->
		<remove id='995'/><!-- 疾襲衝擊2 -->
	</skill>
	<skill id='10270'><!-- 最終之力 -->
		<remove id='121'/><!-- 戰鬥咆哮 -->
		<remove id='441'/><!-- 無想鬥魂 -->
		<remove id='1561'/><!-- 戰嚎 -->
		<remove id='20006'/><!-- 靈魂咆哮 -->
	</skill>
	<skill id='10271'><!-- 強力激怒 -->
		<remove id='286'/><!-- 激怒 -->
		<remove id='503'/><!-- 輕蔑 -->
	</skill>
	<skill id='10273'><!-- 疾速卸除武器 -->
		<remove id='775'/><!-- 武器封鎖 -->
		<remove id='794'/><!-- 集體卸除武器 -->
	</skill>
	<skill id='10274'><!-- 狂暴化 -->
		<remove id='25'/><!-- 召喚機械高崙 -->
		<remove id='130'/><!-- 顫慄激戰 -->
		<remove id='176'/><!-- 狂暴加護 -->
		<remove id='292'/><!-- 野牛圖騰靈 -->
		<remove id='297'/><!-- 決鬥者之靈 -->
		<remove id='301'/><!-- 召喚大炸彈 -->
		<remove id='317'/><!-- 專注攻擊 -->
		<remove id='1510'/><!-- 靈魂淨罪 -->
	</skill>
	<skill id='10278'><!-- 憤怒縮減 -->
		<remove id='317'/><!-- 專注攻擊 -->
		<remove id='833'/><!-- 重建之體 -->
	</skill>
	<skill id='10279'><!-- 巨人屏障 -->
		<remove id='34'/><!-- 包紮術 -->
		<remove id='442'/><!-- 波動氣場 -->
		<remove id='443'/><!-- 鬥氣障壁 -->
		<remove id='1514'/><!-- 靈魂屏障 -->
	</skill>
	<skill id='10280'><!-- 鬥力充能 -->
		<remove id='8'/><!-- 波動凝聚 -->
		<remove id='50'/><!-- 凝神聚氣 -->
	</skill>
	<skill id='10286'><!-- 極致抵抗 -->
		<remove id='481'/><!-- 黑暗裝甲 -->
	</skill>
	<skill id='10288'><!-- 劇烈風暴 -->
		<remove id='6'/><!-- 波動衝擊 -->
		<remove id='7'/><!-- 波動風暴 -->
		<remove id='35'/><!-- 力量風暴 -->
		<remove id='54'/><!-- 爆裂衝擊 -->
		<remove id='347'/><!-- 烈震閃 -->
		<remove id='526'/><!-- 諸天之上 -->
	</skill>
	<skill id='10289'><!-- 勇氣之矛 -->
		<remove id='440'/><!-- 勇者之心 -->
		<remove id='485'/><!-- 卸除武器 -->
		<remove id='536'/><!-- 超越之體 -->
	</skill>
	<skill id='10292'><!-- 食人魔戰嚎 -->
		<remove id='94'/><!-- 狂暴戰士 -->
		<remove id='78'/><!-- 戰之狂嚎 -->
		<remove id='109'/><!-- 食人魔圖騰靈 -->
		<remove id='130'/><!-- 顫慄激戰 -->
		<remove id='139'/><!-- 勇氣加護 -->
		<remove id='482'/><!-- 暴怒之魂 -->
		<remove id='500'/><!-- 真 狂戰士 -->
		<remove id='828'/><!-- 表層硬化 -->
		<remove id='829'/><!-- 表革硬化 -->
		<remove id='830'/><!-- 紋刻 -->
	</skill>
	<skill id='10293'><!-- 豹之戰嚎 -->
		<remove id='94'/><!-- 狂暴戰士 -->
		<remove id='78'/><!-- 戰之狂嚎 -->
		<remove id='130'/><!-- 顫慄激戰 -->
		<remove id='139'/><!-- 勇氣加護 -->
		<remove id='282'/><!-- 豹之圖騰靈 -->
		<remove id='482'/><!-- 暴怒之魂 -->
		<remove id='500'/><!-- 真 狂戰士 -->
		<remove id='822'/><!-- 高崙維修 -->
		<remove id='823'/><!-- 強大之力 -->
		<remove id='824'/><!-- 防禦武裝 -->
	</skill>
	<skill id='10294'><!-- 兔之戰嚎 -->
		<remove id='298'/><!-- 兔子圖騰靈 -->
		<remove id='451'/><!-- 波動疾行 -->
		<remove id='823'/><!-- 強大之力 -->
	</skill>
	<skill id='10295'><!-- 鷹之戰嚎 -->
		<remove id='425'/><!-- 獵鷹圖騰靈 -->
	</skill>
	<skill id='10296'><!-- 狩者之魂 -->
		<remove id='87'/><!-- 動物剋星 -->
		<remove id='104'/><!-- 植物剋星 -->
		<remove id='359'/><!-- 狩者之眼 -->
	</skill>
	<skill id='10297'><!-- 殺手之魂 -->
		<remove id='80'/><!-- 怪獸剋星 -->
		<remove id='88'/><!-- 龍族剋星 -->
		<remove id='360'/><!-- 殺手之眼 -->
	</skill>
	<skill id='10298'><!-- 強力再生 -->
		<remove id='181'/><!-- 再生術 -->
		<remove id='833'/><!-- 重建之體 -->
	</skill>
<!-- 覺醒技能-歐瑟遊俠 -->
	<skill id='10501'><!-- 極致精通匕首 -->
		<remove id='168'/><!-- 攻擊加速 -->
		<remove id='205'/><!-- 精通劍鈍兵器1 -->
		<remove id='209'/><!-- 精通匕首 -->
		<remove id='216'/><!-- 精通長戟 -->
		<remove id='217'/><!-- 精通劍鈍兵器2 -->
		<remove id='257'/><!-- 精通劍鈍兵器3 -->
		<remove id='330'/><!-- 精通戰技 -->
		<remove id='432'/><!-- 殺手本能 -->
	</skill>
	<skill id='10502'><!-- 極致精通雙匕首 -->
		<remove id='952'/><!-- 收藏家的經驗 -->
	</skill>
	<skill id='10503'><!-- 極致精通輕裝甲 -->
		<remove id='173'/><!-- 特技精通 -->
		<remove id='225'/><!-- 迴避移動 -->
		<remove id='227'/><!-- 精通輕裝甲1 -->
